apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      component: backend-feed
  template:    
    metadata:
      name: udagram-api-feed-deployment-spec
      labels:
        component: backend-feed
    spec:
      containers:
        - name: backend-feed
          image:  liadioluwaseun/udagram-api-feed:latest
          volumeMounts:
            - name: aws-secret
              mountPath: /root/.aws
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagram-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagram-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key:  POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key:  POSTGRES_HOST
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key:  AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key:  AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key:  AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key:  JWT_SECRET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key: URL
      volumes:
        - name: aws-secret
          secret:
            secretName: udagram-aws-secret  
  replicas: 1